### PR TITLE
feat: disable row hiding & use button state

### PR DESCRIPTION
**Pull request by silvercondor**

### CODE REVIEW

**Comment by Deepsvyas** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
erain9, @Chisaaato, @chrisalexadams, @ExpressGit, @Mithrilwoodrat, @odyslam, @mandaether, @AbdulMalikDev, @evelynEdison, @rayanht, @rianhughes, @mayocca, @xiaohaibin, @Antonito, @arekgotfryd, @pRoy24, @yulidai, @evancasey, @DawN1ng, @uzairgheewala, @blobitty, @tker90, @okuai, @ccyanxyz, @seansean11, @takahiro-prog, @benschac, @octogene, @Aozh1, @gakuzen, @eulerbeat5, @Ninja-mann, @lastshodan, @ares0x, @fala13, @cryptotriv, @greyireland, @kazani-351, @liamzebedee, @trojan0x, @levi0214, @hjo1620, @laike, @0xJchen, @htadashi, @matthope1, @tlkahn, @gladiopeace, @elessarrr, @beanaas

**Comment by GitSyncPromedia** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Theo6890, @pick7, @jerryge, @0xStabby, @Timidan, @sagarjethi, @cyberbhoi, @rongpan, @Haruxe, @Holt666, @tmol0003, @rcstanciu, @DeFixAndEr, @akhilmantha, @LeoVS09, @ku-ra, @Decision2016, @0xFondue, @rodneyxr, @JeffCX, @he1m4n6a, @Mariesnlk, @HAOYUatHZ, @kimson99, @u2, @basharabdullah, @0x1355, @case7026, @kangchihlun, @MrSaints, @odanado, @PRavaga, @DennisDv24, @Wyatt-Stanke, @lane2, @haskel, @professeurfarnsworth, @0xK4d1r, @ingenuine, @zqzqz, @TheKnightCoder, @Hasiwansui, @elestu, @Liao1, @oceanyun78, @AaHUANG1998, @jimmyllee098, @imhexagram, @mul1sh, @marciolscoutinho

**Comment by GitSyncPromedia** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
0x7An, @xBA5ED, @NickEU, @innertiaJP, @aryamalvrz, @garthmortensen, @seteri111, @tkowalczyk, @daviwesley, @eferbarn, @SamGMK, @FacundoZS, @sify21, @michwqy, @metagameindustries, @ignaval, @jmg-duarte, @MicroCreatorALLA, @y3zha, @mrhouzlane, @ebnth-zorea, @Neetbear, @collisioncataclysm, @seekersoftec, @Kaushal1011, @0xKoda, @exp7l, @multichainmagus, @m0rty01, @thefrisson, @m4ns0ur, @elatoskinas, @JorgeMadson, @onsails, @naugue, @yjc801, @kevin-fruitful, @bossjoker1, @a00012025, @ehsanshojaeiiii, @Confucian-e, @iLVino, @demondvn, @npjd, @sanqima, @PavelNaydanov, @nikita, @Sntx-bl0w, @fredfeng, @aroralanuk

**Comment by Deepsvyas** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
CootieShots, @zhiwei-w-luo, @Butters3388214, @mayooear, @0xMonolith, @luojeth, @Chinjoy, @maldiohead, @mooremo, @appleseed-iii, @GlobalCryptoSolutions, @knightowen, @Monichre, @kaliwdsn, @l-henri, @DrakeSebass, @cdifranco1, @okcomputerb, @degencodebeast, @ligulfzhou, @jpark0315, @beans42, @Klugekluge67, @leoasah2047, @pcaversaccio, @dbulnes, @lucasboy66, @GlebRadchenko, @moesy, @gtsigner, @leighvl, @Timidan, @Dvisacker, @zhaifg, @BigwigsNFT, @jandykwan, @DataCrunchWizard, @HackMogador, @superposition, @lay-z, @krajarajan, @yukairex, @0xtaosu, @chirag-bgh, @NotAlfred

**Pull request merged**
